name: HAMQTT Integration Workflow - IntegrationName

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/integration-name.yml
      - IntegrationName/**

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    name: Integration Workflow
    uses: mavanmanen/HAMQTT.Net/.github/workflows/hamqtt-integration-workflow.yml@main
    with:
      name: IntegrationName
      directory: ./IntegrationName/