<#
.SYNOPSIS
    Cleans generated artifacts and temporary files.
.DESCRIPTION
    Removes files generated by the 'deploy' and 'update' scripts:
    1. Production artifacts (root docker-compose.yml).
    2. Temporary update/clone folders.
    3. Backup scripts (hamqtt.ps1.old).
    
    NOTE: 
    - Does NOT remove .NET artifacts (bin/obj).
    - Does NOT remove .env files or source configuration to preserve secrets/customization.
#>

$ErrorActionPreference = "Stop"

# --- Import Shared Functions & Assert Wrapper ---
. "$PSScriptRoot/Common-Utils.ps1"
Assert-HamqttWrapper

Write-Host "🧹 Starting Project Clean..." -ForegroundColor Cyan

# --- 1. Clean Root Artifacts ---
$RootTargets = @(
    "docker-compose.yml",       # Generated by 'deploy'
    "hamqtt.ps1.old",           # Generated by 'update'
    "_hamqtt_temp_clone",       # Temp bootstrap folder
    "_hamqtt_update_temp"       # Temp update folder
)

foreach ($Target in $RootTargets) {
    $Path = Join-Path $ProjectRoot $Target
    if (Test-Path $Path) {
        try {
            if (Test-Path $Path -PathType Container) {
                Remove-Item -Path $Path -Recurse -Force -ErrorAction Stop
            } else {
                Remove-Item -Path $Path -Force -ErrorAction Stop
            }
            Write-Host "   🗑️  Deleted: $Target" -ForegroundColor Gray
        } catch {
            Write-Warning "   ⚠️  Could not delete $Target : $_"
        }
    }
}

Write-Host "`n✨ Clean Complete!" -ForegroundColor Cyan